platform :ios, '8.0'

target 'qulicai' do

pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'YTKNetwork'
pod 'YYKit'
pod 'SimpleKeychain'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'TOWebViewController'
pod 'WZLBadge'

pod 'MTLog'

end

